import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Language =
  | 'english'
  | 'arabic'
  | 'urdu'
  | 'french'
  | 'turkish'
  | 'indonesian'
  | 'malay'
  | 'spanish';

const translations = {
  english: {
    settings: 'Settings',
    notifications: 'Notifications',
    enableNotifications: 'Enable Notifications',
    prayerAlerts: 'Prayer Time Alerts',
    reminderBeforePrayer: 'Reminder before prayer',
    calculationMethod: 'Calculation Method',
    prayerCalculation: 'Prayer Calculation',
    darkMode: 'Dark Mode',
    appearance: 'Appearance',
    language: 'Language',
    appLanguage: 'App Language',
    locationSettings: 'Location Settings',
    useAutoLocation: 'Use Auto-location',
    setManualLocation: 'Set Manual Location',
    aboutSupport: 'About & Support',
    aboutThisApp: 'About this App',
    helpSupport: 'Help & Support',
    saveSettings: 'Save Settings',
    resetDefault: 'Reset to Default',
    prayerTimes: 'Prayer Times',
    findMosque: 'Find Nearest Mosque',
    qiblaDirection: 'Qibla Direction',
    quran: 'Quran',
    zakat: 'Zakat',
    zakatNotifications: 'Zakat Notifications',
    zakatFrequency: 'Frequency',
    settingsTab: 'Settings',
    fajr: 'Fajr',
    sunrise: 'Sunrise',
    dhuhr: 'Dhuhr',
    asr: 'Asr',
    maghrib: 'Maghrib',
    isha: 'Isha',
    nextPrayer: 'Next Prayer',
    todaysPrayerTimes: "Today's Prayer Times",
    remaining: 'remaining',
    loadingPrayerTimes: 'Loading prayer times...',
    tapToRetry: 'Tap to retry',
    minutes: 'minutes',
    methodMWL: 'Muslim World League',
    methodISNA: 'ISNA (North America)',
    methodEgyptian: 'Egyptian Authority',
    methodKarachi: 'University of Karachi',
    methodMakkah: 'Umm al-Qura, Makkah',
    findCharity: 'Find a Charity',
    selectCause: 'Select Cause',
    hungerRelief: 'Hunger Relief',
    palestine: 'Palestine',
    donateQuran: "Donate Qur'an",
    warRelief: 'War Relief',
    favorites: 'Favorites',
    current: 'Current',
    islamicCalendar: 'Islamic Calendar',
    upcomingEvents: 'Upcoming Islamic Events',
  },
  arabic: {
    settings: 'الإعدادات',
    notifications: 'الإشعارات',
    enableNotifications: 'تفعيل الإشعارات',
    prayerAlerts: 'تنبيهات الصلاة',
    reminderBeforePrayer: 'تذكير قبل الصلاة',
    calculationMethod: 'طريقة الحساب',
    prayerCalculation: 'حساب الصلاة',
    darkMode: 'الوضع الداكن',
    appearance: 'المظهر',
    language: 'اللغة',
    appLanguage: 'لغة التطبيق',
    locationSettings: 'إعدادات الموقع',
    useAutoLocation: 'الموقع التلقائي',
    setManualLocation: 'تحديد الموقع يدوياً',
    aboutSupport: 'حول والدعم',
    aboutThisApp: 'حول هذا التطبيق',
    helpSupport: 'المساعدة والدعم',
    saveSettings: 'حفظ الإعدادات',
    resetDefault: 'إعادة الضبط',
    prayerTimes: 'مواقيت الصلاة',
    findMosque: 'أقرب مسجد',
    qiblaDirection: 'اتجاه القبلة',
    quran: 'القرآن',
    zakat: 'الزكاة',
    zakatNotifications: 'تنبيهات الزكاة',
    zakatFrequency: 'التكرار',
    settingsTab: 'الإعدادات',
    fajr: 'الفجر',
    sunrise: 'الشروق',
    dhuhr: 'الظهر',
    asr: 'العصر',
    maghrib: 'المغرب',
    isha: 'العشاء',
    nextPrayer: 'الصلاة التالية',
    todaysPrayerTimes: 'مواقيت صلاة اليوم',
    remaining: 'متبقي',
    loadingPrayerTimes: 'جاري تحميل مواقيت الصلاة...',
    tapToRetry: 'اضغط للمحاولة مرة أخرى',
    minutes: 'دقائق',
    methodMWL: 'رابطة العالم الإسلامي',
    methodISNA: 'الجمعية الإسلامية لأمريكا الشمالية',
    methodEgyptian: 'الهيئة المصرية',
    methodKarachi: 'جامعة كراتشي',
    methodMakkah: 'أم القرى، مكة',
    findCharity: 'ابحث عن جمعية خيرية',
    selectCause: 'اختر سبب التبرع',
    hungerRelief: 'إغاثة الجوع',
    palestine: 'فلسطين',
    donateQuran: 'تبرع بالمصحف',
    warRelief: 'إغاثة الحرب',
    favorites: 'المفضلة',
    current: 'الحالية',
    islamicCalendar: 'التقويم الهجري',
    upcomingEvents: 'الأحداث الإسلامية القادمة',
  },
  urdu: {
    settings: 'سیٹنگز',
    notifications: 'اطلاعات',
    enableNotifications: 'اطلاعات فعال کریں',
    prayerAlerts: 'نماز کے انتباہات',
    reminderBeforePrayer: 'نماز سے قبل یاددہانی',
    calculationMethod: 'حساب کا طریقہ',
    prayerCalculation: 'نماز کا حساب',
    darkMode: 'ڈارک موڈ',
    appearance: 'ظاہری شکل',
    language: 'زبان',
    appLanguage: 'ایپ کی زبان',
    locationSettings: 'مقام کی سیٹنگز',
    useAutoLocation: 'خودکار مقام استعمال کریں',
    setManualLocation: 'مقام دستی طور پر سیٹ کریں',
    aboutSupport: 'ایپ کے بارے میں اور سپورٹ',
    aboutThisApp: 'ایپ کے بارے میں',
    helpSupport: 'مدد اور سپورٹ',
    saveSettings: 'سیٹنگز محفوظ کریں',
    resetDefault: 'ڈیفالٹ پر ری سیٹ',
    prayerTimes: 'نماز کے اوقات',
    findMosque: 'قریبی مسجد تلاش کریں',
    qiblaDirection: 'سمت قبلہ',
    quran: 'قرآن',
    zakat: 'زکوٰۃ',
    zakatNotifications: 'زکوٰۃ کی اطلاعات',
    zakatFrequency: 'تکرار',
    settingsTab: 'سیٹنگز',
    fajr: 'فجر',
    sunrise: 'طلوع آفتاب',
    dhuhr: 'ظہر',
    asr: 'عصر',
    maghrib: 'مغرب',
    isha: 'عشاء',
    nextPrayer: 'اگلی نماز',
    todaysPrayerTimes: 'آج کے نماز کے اوقات',
    remaining: 'باقی',
    loadingPrayerTimes: 'نماز کے اوقات لوڈ ہو رہے ہیں...',
    tapToRetry: 'دوبارہ کوشش کے لئے ٹیپ کریں',
    minutes: 'منٹ',
    methodMWL: 'مسلم ورلڈ لیگ',
    methodISNA: 'اسلامک سوسائٹی نارتھ امریکہ',
    methodEgyptian: 'مصری اتھارٹی',
    methodKarachi: 'یونیورسٹی آف کراچی',
    methodMakkah: 'ام القریٰ، مکہ',
    findCharity: 'خیراتی ادارہ تلاش کریں',
    selectCause: 'سبب منتخب کریں',
    hungerRelief: 'بھوک مٹانے کیلئے',
    palestine: 'فلسطین',
    donateQuran: 'قرآن عطیہ کریں',
    warRelief: 'جنگ زدگان کی مدد',
    favorites: 'پسندیدہ',
    current: 'موجودہ',
    islamicCalendar: 'اسلامی تقویم',
    upcomingEvents: 'آنے والے اسلامی مواقع',
  },
  french: {
    settings: 'Paramètres',
    notifications: 'Notifications',
    enableNotifications: 'Activer les notifications',
    prayerAlerts: 'Alertes de prière',
    reminderBeforePrayer: 'Rappel avant la prière',
    calculationMethod: 'Méthode de calcul',
    prayerCalculation: 'Calcul de la prière',
    darkMode: 'Mode sombre',
    appearance: 'Apparence',
    language: 'Langue',
    appLanguage: "Langue de l'app", 
    locationSettings: 'Paramètres de localisation',
    useAutoLocation: 'Utiliser la localisation auto',
    setManualLocation: 'Définir la localisation',
    aboutSupport: 'À propos et support',
    aboutThisApp: 'À propos de cette app',
    helpSupport: 'Aide et support',
    saveSettings: 'Sauvegarder',
    resetDefault: 'Réinitialiser',
    prayerTimes: 'Heures de prière',
    findMosque: 'Mosquée la plus proche',
    qiblaDirection: 'Direction de la Qibla',
    quran: 'Coran',
    zakat: 'Zakat',
    zakatNotifications: 'Notifications de zakat',
    zakatFrequency: 'Fréquence',
    settingsTab: 'Paramètres',
    fajr: 'Fajr',
    sunrise: 'Lever du soleil',
    dhuhr: 'Dhuhr',
    asr: 'Asr',
    maghrib: 'Maghreb',
    isha: 'Isha',
    nextPrayer: 'Prochaine prière',
    todaysPrayerTimes: 'Heures de prière du jour',
    remaining: 'restant',
    loadingPrayerTimes: 'Chargement des heures de prière...',
    tapToRetry: 'Appuyez pour réessayer',
    minutes: 'minutes',
    methodMWL: 'Ligue Musulmane Mondiale',
    methodISNA: 'ISNA (Amérique du Nord)',
    methodEgyptian: 'Autorité égyptienne',
    methodKarachi: 'Université de Karachi',
    methodMakkah: 'Oum al-Qoura, La Mecque',
    findCharity: 'Trouver une association',
    selectCause: 'Choisir une cause',
    hungerRelief: 'Lutte contre la faim',
    palestine: 'Palestine',
    donateQuran: 'Offrir un Coran',
    warRelief: 'Aide aux victimes de guerre',
    favorites: 'Favoris',
    current: 'Actuelle',
    islamicCalendar: 'Calendrier islamique',
    upcomingEvents: 'Événements islamiques à venir',
  },
  turkish: {
    settings: 'Ayarlar',
    notifications: 'Bildirimler',
    enableNotifications: 'Bildirimleri etkinleştir',
    prayerAlerts: 'Namaz uyarıları',
    reminderBeforePrayer: 'Namazdan önce hatırlatma',
    calculationMethod: 'Hesaplama yöntemi',
    prayerCalculation: 'Namaz hesaplama',
    darkMode: 'Karanlık mod',
    appearance: 'Görünüm',
    language: 'Dil',
    appLanguage: 'Uygulama dili',
    locationSettings: 'Konum ayarları',
    useAutoLocation: 'Otomatik konum kullan',
    setManualLocation: 'Manuel konum ayarla',
    aboutSupport: 'Hakkında ve destek',
    aboutThisApp: 'Uygulama hakkında',
    helpSupport: 'Yardım ve destek',
    saveSettings: 'Ayarları kaydet',
    resetDefault: 'Varsayılanlara dön',
    prayerTimes: 'Namaz Vakitleri',
    findMosque: 'En Yakın Cami',
    qiblaDirection: 'Kıble Yönü',
    quran: 'Kur’an',
    zakat: 'Zekat',
    zakatNotifications: 'Zekat Bildirimleri',
    zakatFrequency: 'Siklik',
    settingsTab: 'Ayarlar',
    fajr: 'Sabah',
    sunrise: 'Güneş',
    dhuhr: 'Öğle',
    asr: 'İkindi',
    maghrib: 'Akşam',
    isha: 'Yatsı',
    nextPrayer: 'Sonraki Namaz',
    todaysPrayerTimes: 'Bugünün Namaz Vakitleri',
    remaining: 'kaldı',
    loadingPrayerTimes: 'Namaz vakitleri yükleniyor...',
    tapToRetry: 'Tekrar denemek için dokun',
    minutes: 'dakika',
    methodMWL: 'Dünya Müslüman Ligi',
    methodISNA: 'ISNA (Kuzey Amerika)',
    methodEgyptian: 'Mısır Otoritesi',
    methodKarachi: 'Karaçi Üniversitesi',
    methodMakkah: "Ümmü'l Kurâ, Mekke",
    findCharity: 'Bir Hayır Kurumu Bul',
    selectCause: 'Sebep Seç',
    hungerRelief: 'Açlık Yardımı',
    palestine: 'Filistin',
    donateQuran: "Kur'an Bağışı",
    warRelief: 'Savaş Yardımı',
    favorites: 'Favoriler',
    current: 'Güncel',
    islamicCalendar: 'İslami Takvim',
    upcomingEvents: 'Yaklaşan İslami Etkinlikler',
  },
  indonesian: {
    settings: 'Pengaturan',
    notifications: 'Notifikasi',
    enableNotifications: 'Aktifkan Notifikasi',
    prayerAlerts: 'Pengingat Waktu Shalat',
    reminderBeforePrayer: 'Pengingat sebelum shalat',
    calculationMethod: 'Metode Perhitungan',
    prayerCalculation: 'Perhitungan Shalat',
    darkMode: 'Mode Gelap',
    appearance: 'Tampilan',
    language: 'Bahasa',
    appLanguage: 'Bahasa Aplikasi',
    locationSettings: 'Pengaturan Lokasi',
    useAutoLocation: 'Gunakan Lokasi Otomatis',
    setManualLocation: 'Atur Lokasi Manual',
    aboutSupport: 'Tentang & Dukungan',
    aboutThisApp: 'Tentang Aplikasi Ini',
    helpSupport: 'Bantuan & Dukungan',
    saveSettings: 'Simpan Pengaturan',
    resetDefault: 'Kembali ke Default',
    prayerTimes: 'Waktu Shalat',
    findMosque: 'Cari Masjid Terdekat',
    qiblaDirection: 'Arah Kiblat',
    quran: "Qur'an",
    zakat: 'Zakat',
    zakatNotifications: 'Notifikasi Zakat',
    zakatFrequency: 'Frekuensi',
    settingsTab: 'Pengaturan',
    fajr: 'Subuh',
    sunrise: 'Matahari Terbit',
    dhuhr: 'Dzuhur',
    asr: 'Ashar',
    maghrib: 'Maghrib',
    isha: 'Isya',
    nextPrayer: 'Shalat Berikutnya',
    todaysPrayerTimes: 'Waktu Shalat Hari Ini',
    remaining: 'tersisa',
    loadingPrayerTimes: 'Memuat waktu shalat...',
    tapToRetry: 'Ketuk untuk mencoba lagi',
    minutes: 'menit',
    methodMWL: 'Liga Muslim Dunia',
    methodISNA: 'ISNA (Amerika Utara)',
    methodEgyptian: 'Otoritas Mesir',
    methodKarachi: 'Universitas Karachi',
    methodMakkah: 'Umm al-Qura, Mekkah',
    findCharity: 'Cari Amal',
    selectCause: 'Pilih Tujuan',
    hungerRelief: 'Bantuan Kelaparan',
    palestine: 'Palestina',
    donateQuran: "Donasi Al-Qur'an",
    warRelief: 'Bantuan Perang',
    current: 'Saat Ini',
  },
  malay: {
    settings: 'Tetapan',
    notifications: 'Pemberitahuan',
    enableNotifications: 'Aktifkan Pemberitahuan',
    prayerAlerts: 'Peringatan Waktu Solat',
    reminderBeforePrayer: 'Peringatan sebelum solat',
    calculationMethod: 'Kaedah Pengiraan',
    prayerCalculation: 'Pengiraan Solat',
    darkMode: 'Mod Gelap',
    appearance: 'Penampilan',
    language: 'Bahasa',
    appLanguage: 'Bahasa Aplikasi',
    locationSettings: 'Tetapan Lokasi',
    useAutoLocation: 'Guna Lokasi Auto',
    setManualLocation: 'Tetapkan Lokasi Manual',
    aboutSupport: 'Tentang & Sokongan',
    aboutThisApp: 'Tentang Aplikasi Ini',
    helpSupport: 'Bantuan & Sokongan',
    saveSettings: 'Simpan Tetapan',
    resetDefault: 'Set Semula',
    prayerTimes: 'Waktu Solat',
    findMosque: 'Cari Masjid Terdekat',
    qiblaDirection: 'Arah Kiblat',
    quran: 'Quran',
    zakat: 'Zakat',
    zakatNotifications: 'Notifikasi Zakat',
    zakatFrequency: 'Kekerapan',
    settingsTab: 'Tetapan',
    fajr: 'Subuh',
    sunrise: 'Terbit Matahari',
    dhuhr: 'Zohor',
    asr: 'Asar',
    maghrib: 'Maghrib',
    isha: 'Isyak',
    nextPrayer: 'Solat Seterusnya',
    todaysPrayerTimes: 'Waktu Solat Hari Ini',
    remaining: 'tinggal',
    loadingPrayerTimes: 'Memuat waktu solat...',
    tapToRetry: 'Ketuk untuk cuba lagi',
    minutes: 'minit',
    methodMWL: 'Liga Muslim Dunia',
    methodISNA: 'ISNA (Amerika Utara)',
    methodEgyptian: 'Pihak Berkuasa Mesir',
    methodKarachi: 'Universiti Karachi',
    methodMakkah: 'Umm al-Qura, Makkah',
    findCharity: 'Cari Amal',
    selectCause: 'Pilih Tujuan',
    hungerRelief: 'Bantuan Kelaparan',
    palestine: 'Palestin',
    donateQuran: 'Derma Al-Quran',
    warRelief: 'Bantuan Perang',
    current: 'Semasa',
  },
  spanish: {
    settings: 'Configuración',
    notifications: 'Notificaciones',
    enableNotifications: 'Activar Notificaciones',
    prayerAlerts: 'Alertas de Oración',
    reminderBeforePrayer: 'Recordatorio antes de la oración',
    calculationMethod: 'Método de Cálculo',
    prayerCalculation: 'Cálculo de Oración',
    darkMode: 'Modo Oscuro',
    appearance: 'Apariencia',
    language: 'Idioma',
    appLanguage: 'Idioma de la App',
    locationSettings: 'Configuración de Ubicación',
    useAutoLocation: 'Usar Ubicación Automática',
    setManualLocation: 'Establecer Ubicación Manual',
    aboutSupport: 'Acerca de & Soporte',
    aboutThisApp: 'Acerca de esta App',
    helpSupport: 'Ayuda & Soporte',
    saveSettings: 'Guardar Configuración',
    resetDefault: 'Restablecer Predeterminado',
    prayerTimes: 'Horarios de Oración',
    findMosque: 'Buscar Mezquita Cercana',
    qiblaDirection: 'Dirección de la Qibla',
    quran: 'Corán',
    zakat: 'Zakat',
    zakatNotifications: 'Notificaciones de Zakat',
    zakatFrequency: 'Frecuencia',
    settingsTab: 'Configuración',
    fajr: 'Fajr',
    sunrise: 'Amanecer',
    dhuhr: 'Dhuhr',
    asr: 'Asr',
    maghrib: 'Maghrib',
    isha: 'Isha',
    nextPrayer: 'Próxima Oración',
    todaysPrayerTimes: 'Horarios de Oración de Hoy',
    remaining: 'restante',
    loadingPrayerTimes: 'Cargando horarios de oración...',
    tapToRetry: 'Toque para reintentar',
    minutes: 'minutos',
    methodMWL: 'Liga Musulmana Mundial',
    methodISNA: 'ISNA (Norteamérica)',
    methodEgyptian: 'Autoridad Egipcia',
    methodKarachi: 'Universidad de Karachi',
    methodMakkah: 'Umm al-Qura, Meca',
    findCharity: 'Encontrar Caridad',
    selectCause: 'Seleccionar Causa',
    hungerRelief: 'Ayuda Contra el Hambre',
    palestine: 'Palestina',
    donateQuran: 'Donar Corán',
    warRelief: 'Ayuda de Guerra',
    current: 'Actual',
  },
} as const;

export type Translations = typeof translations.english;

interface LanguageContextData {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof Translations) => string;
}

const LanguageContext = createContext<LanguageContextData>({
  language: 'english',
  setLanguage: () => {},
  t: (key: keyof Translations) => translations.english[key],
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('english');

  useEffect(() => {
    const loadLanguage = async () => {
      try {
        const saved = await AsyncStorage.getItem('language');
        if (saved) {
          setLanguageState(saved as Language);
        }
      } catch (e) {
        console.error('Failed to load language', e);
      }
    };
    loadLanguage();
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    AsyncStorage.setItem('language', lang).catch((e) =>
      console.error('Failed to save language', e)
    );
  };

  const t = (key: keyof Translations) => {
    return translations[language][key] || translations.english[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);

