import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Language = 'english' | 'arabic' | 'urdu' | 'french' | 'turkish';

const translations = {
  english: {
    settings: 'Settings',
    notifications: 'Notifications',
    enableNotifications: 'Enable Notifications',
    prayerAlerts: 'Prayer Time Alerts',
    reminderBeforePrayer: 'Reminder before prayer',
    calculationMethod: 'Calculation Method',
    prayerCalculation: 'Prayer Calculation',
    darkMode: 'Dark Mode',
    appearance: 'Appearance',
    language: 'Language',
    appLanguage: 'App Language',
    locationSettings: 'Location Settings',
    useAutoLocation: 'Use Auto-location',
    setManualLocation: 'Set Manual Location',
    aboutSupport: 'About & Support',
    aboutThisApp: 'About this App',
    helpSupport: 'Help & Support',
    saveSettings: 'Save Settings',
    resetDefault: 'Reset to Default',
    prayerTimes: 'Prayer Times',
    findMosque: 'Find Nearest Mosque',
    qiblaDirection: 'Qibla Direction',
    quran: 'Quran',
    zakat: 'Zakat',
    zakatNotifications: 'Zakat Notifications',
    zakatFrequency: 'Frequency',
    fajrAlarm: 'Fajr Wake-up Alarm',
    fajrAlarmOffset: 'Minutes before Fajr',
    ramadanReminders: 'Ramadan Reminders',
    ramadanReminderTime: 'Reminder time',
    settingsTab: 'Settings',
    fajr: 'Fajr',
    sunrise: 'Sunrise',
    dhuhr: 'Dhuhr',
    asr: 'Asr',
    maghrib: 'Maghrib',
    isha: 'Isha',
    nextPrayer: 'Next Prayer',
    todaysPrayerTimes: "Today's Prayer Times",
    remaining: 'remaining',
    loadingPrayerTimes: 'Loading prayer times...',
    tapToRetry: 'Tap to retry',
    minutes: 'minutes',
    methodMWL: 'Muslim World League',
    methodISNA: 'ISNA (North America)',
    methodEgyptian: 'Egyptian Authority',
    methodKarachi: 'University of Karachi',
    methodMakkah: 'Umm al-Qura, Makkah',
    findCharity: 'Find a Charity',
    selectCause: 'Select Cause',
    hungerRelief: 'Hunger Relief',
    palestine: 'Palestine',
    donateQuran: "Donate Qur'an",
    warRelief: 'War Relief',
    current: 'Current',
  },
  arabic: {
    settings: 'الإعدادات',
    notifications: 'الإشعارات',
    enableNotifications: 'تفعيل الإشعارات',
    prayerAlerts: 'تنبيهات الصلاة',
    reminderBeforePrayer: 'تذكير قبل الصلاة',
    calculationMethod: 'طريقة الحساب',
    prayerCalculation: 'حساب الصلاة',
    darkMode: 'الوضع الداكن',
    appearance: 'المظهر',
    language: 'اللغة',
    appLanguage: 'لغة التطبيق',
    locationSettings: 'إعدادات الموقع',
    useAutoLocation: 'الموقع التلقائي',
    setManualLocation: 'تحديد الموقع يدوياً',
    aboutSupport: 'حول والدعم',
    aboutThisApp: 'حول هذا التطبيق',
    helpSupport: 'المساعدة والدعم',
    saveSettings: 'حفظ الإعدادات',
    resetDefault: 'إعادة الضبط',
    prayerTimes: 'مواقيت الصلاة',
    findMosque: 'أقرب مسجد',
    qiblaDirection: 'اتجاه القبلة',
    quran: 'القرآن',
    zakat: 'الزكاة',
    zakatNotifications: 'تنبيهات الزكاة',
    zakatFrequency: 'التكرار',
    fajrAlarm: 'تنبيه فجر للاستيقاظ',
    fajrAlarmOffset: 'دقائق قبل الفجر',
    ramadanReminders: 'تذكيرات رمضان',
    ramadanReminderTime: 'وقت التذكير',
    settingsTab: 'الإعدادات',
    fajr: 'الفجر',
    sunrise: 'الشروق',
    dhuhr: 'الظهر',
    asr: 'العصر',
    maghrib: 'المغرب',
    isha: 'العشاء',
    nextPrayer: 'الصلاة التالية',
    todaysPrayerTimes: 'مواقيت صلاة اليوم',
    remaining: 'متبقي',
    loadingPrayerTimes: 'جاري تحميل مواقيت الصلاة...',
    tapToRetry: 'اضغط للمحاولة مرة أخرى',
    minutes: 'دقائق',
    methodMWL: 'رابطة العالم الإسلامي',
    methodISNA: 'الجمعية الإسلامية لأمريكا الشمالية',
    methodEgyptian: 'الهيئة المصرية',
    methodKarachi: 'جامعة كراتشي',
    methodMakkah: 'أم القرى، مكة',
    findCharity: 'ابحث عن جمعية خيرية',
    selectCause: 'اختر سبب التبرع',
    hungerRelief: 'إغاثة الجوع',
    palestine: 'فلسطين',
    donateQuran: 'تبرع بالمصحف',
    warRelief: 'إغاثة الحرب',
    current: 'الحالية',
  },
  urdu: {
    settings: 'سیٹنگز',
    notifications: 'اطلاعات',
    enableNotifications: 'اطلاعات فعال کریں',
    prayerAlerts: 'نماز کے انتباہات',
    reminderBeforePrayer: 'نماز سے قبل یاددہانی',
    calculationMethod: 'حساب کا طریقہ',
    prayerCalculation: 'نماز کا حساب',
    darkMode: 'ڈارک موڈ',
    appearance: 'ظاہری شکل',
    language: 'زبان',
    appLanguage: 'ایپ کی زبان',
    locationSettings: 'مقام کی سیٹنگز',
    useAutoLocation: 'خودکار مقام استعمال کریں',
    setManualLocation: 'مقام دستی طور پر سیٹ کریں',
    aboutSupport: 'ایپ کے بارے میں اور سپورٹ',
    aboutThisApp: 'ایپ کے بارے میں',
    helpSupport: 'مدد اور سپورٹ',
    saveSettings: 'سیٹنگز محفوظ کریں',
    resetDefault: 'ڈیفالٹ پر ری سیٹ',
    prayerTimes: 'نماز کے اوقات',
    findMosque: 'قریبی مسجد تلاش کریں',
    qiblaDirection: 'سمت قبلہ',
    quran: 'قرآن',
    zakat: 'زکوٰۃ',
    zakatNotifications: 'زکوٰۃ کی اطلاعات',
    zakatFrequency: 'تکرار',
    fajrAlarm: 'فجر بیداری الارم',
    fajrAlarmOffset: 'فجر سے پہلے منٹ',
    ramadanReminders: 'رمضان یاد دہانی',
    ramadanReminderTime: 'یاد دہانی وقت',
    settingsTab: 'سیٹنگز',
    fajr: 'فجر',
    sunrise: 'طلوع آفتاب',
    dhuhr: 'ظہر',
    asr: 'عصر',
    maghrib: 'مغرب',
    isha: 'عشاء',
    nextPrayer: 'اگلی نماز',
    todaysPrayerTimes: 'آج کے نماز کے اوقات',
    remaining: 'باقی',
    loadingPrayerTimes: 'نماز کے اوقات لوڈ ہو رہے ہیں...',
    tapToRetry: 'دوبارہ کوشش کے لئے ٹیپ کریں',
    minutes: 'منٹ',
    methodMWL: 'مسلم ورلڈ لیگ',
    methodISNA: 'اسلامک سوسائٹی نارتھ امریکہ',
    methodEgyptian: 'مصری اتھارٹی',
    methodKarachi: 'یونیورسٹی آف کراچی',
    methodMakkah: 'ام القریٰ، مکہ',
    findCharity: 'خیراتی ادارہ تلاش کریں',
    selectCause: 'سبب منتخب کریں',
    hungerRelief: 'بھوک مٹانے کیلئے',
    palestine: 'فلسطین',
    donateQuran: 'قرآن عطیہ کریں',
    warRelief: 'جنگ زدگان کی مدد',
    current: 'موجودہ',
  },
  french: {
    settings: 'Paramètres',
    notifications: 'Notifications',
    enableNotifications: 'Activer les notifications',
    prayerAlerts: 'Alertes de prière',
    reminderBeforePrayer: 'Rappel avant la prière',
    calculationMethod: 'Méthode de calcul',
    prayerCalculation: 'Calcul de la prière',
    darkMode: 'Mode sombre',
    appearance: 'Apparence',
    language: 'Langue',
    appLanguage: "Langue de l'app", 
    locationSettings: 'Paramètres de localisation',
    useAutoLocation: 'Utiliser la localisation auto',
    setManualLocation: 'Définir la localisation',
    aboutSupport: 'À propos et support',
    aboutThisApp: 'À propos de cette app',
    helpSupport: 'Aide et support',
    saveSettings: 'Sauvegarder',
    resetDefault: 'Réinitialiser',
    prayerTimes: 'Heures de prière',
    findMosque: 'Mosquée la plus proche',
    qiblaDirection: 'Direction de la Qibla',
    quran: 'Coran',
    zakat: 'Zakat',
    zakatNotifications: 'Notifications de zakat',
    zakatFrequency: 'Fréquence',
    fajrAlarm: 'Alarme Fajr',
    fajrAlarmOffset: 'Minutes avant Fajr',
    ramadanReminders: 'Rappels du Ramadan',
    ramadanReminderTime: 'Heure du rappel',
    settingsTab: 'Paramètres',
    fajr: 'Fajr',
    sunrise: 'Lever du soleil',
    dhuhr: 'Dhuhr',
    asr: 'Asr',
    maghrib: 'Maghreb',
    isha: 'Isha',
    nextPrayer: 'Prochaine prière',
    todaysPrayerTimes: 'Heures de prière du jour',
    remaining: 'restant',
    loadingPrayerTimes: 'Chargement des heures de prière...',
    tapToRetry: 'Appuyez pour réessayer',
    minutes: 'minutes',
    methodMWL: 'Ligue Musulmane Mondiale',
    methodISNA: 'ISNA (Amérique du Nord)',
    methodEgyptian: 'Autorité égyptienne',
    methodKarachi: 'Université de Karachi',
    methodMakkah: 'Oum al-Qoura, La Mecque',
    findCharity: 'Trouver une association',
    selectCause: 'Choisir une cause',
    hungerRelief: 'Lutte contre la faim',
    palestine: 'Palestine',
    donateQuran: 'Offrir un Coran',
    warRelief: 'Aide aux victimes de guerre',
    current: 'Actuelle',
  },
  turkish: {
    settings: 'Ayarlar',
    notifications: 'Bildirimler',
    enableNotifications: 'Bildirimleri etkinleştir',
    prayerAlerts: 'Namaz uyarıları',
    reminderBeforePrayer: 'Namazdan önce hatırlatma',
    calculationMethod: 'Hesaplama yöntemi',
    prayerCalculation: 'Namaz hesaplama',
    darkMode: 'Karanlık mod',
    appearance: 'Görünüm',
    language: 'Dil',
    appLanguage: 'Uygulama dili',
    locationSettings: 'Konum ayarları',
    useAutoLocation: 'Otomatik konum kullan',
    setManualLocation: 'Manuel konum ayarla',
    aboutSupport: 'Hakkında ve destek',
    aboutThisApp: 'Uygulama hakkında',
    helpSupport: 'Yardım ve destek',
    saveSettings: 'Ayarları kaydet',
    resetDefault: 'Varsayılanlara dön',
    prayerTimes: 'Namaz Vakitleri',
    findMosque: 'En Yakın Cami',
    qiblaDirection: 'Kıble Yönü',
    quran: 'Kur’an',
    zakat: 'Zekat',
    zakatNotifications: 'Zekat Bildirimleri',
    zakatFrequency: 'Siklik',
    fajrAlarm: 'Fecir Uyarı Alarmı',
    fajrAlarmOffset: 'Fecirden önceki dakika',
    ramadanReminders: 'Ramazan Hatırlatmaları',
    ramadanReminderTime: 'Hatırlatma saati',
    settingsTab: 'Ayarlar',
    fajr: 'Sabah',
    sunrise: 'Güneş',
    dhuhr: 'Öğle',
    asr: 'İkindi',
    maghrib: 'Akşam',
    isha: 'Yatsı',
    nextPrayer: 'Sonraki Namaz',
    todaysPrayerTimes: 'Bugünün Namaz Vakitleri',
    remaining: 'kaldı',
    loadingPrayerTimes: 'Namaz vakitleri yükleniyor...',
    tapToRetry: 'Tekrar denemek için dokun',
    minutes: 'dakika',
    methodMWL: 'Dünya Müslüman Ligi',
    methodISNA: 'ISNA (Kuzey Amerika)',
    methodEgyptian: 'Mısır Otoritesi',
    methodKarachi: 'Karaçi Üniversitesi',
    methodMakkah: "Ümmü'l Kurâ, Mekke",
    findCharity: 'Bir Hayır Kurumu Bul',
    selectCause: 'Sebep Seç',
    hungerRelief: 'Açlık Yardımı',
    palestine: 'Filistin',
    donateQuran: "Kur'an Bağışı",
    warRelief: 'Savaş Yardımı',
    current: 'Güncel',
  },
} as const;

export type Translations = typeof translations.english;

interface LanguageContextData {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof Translations) => string;
}

const LanguageContext = createContext<LanguageContextData>({
  language: 'english',
  setLanguage: () => {},
  t: (key: keyof Translations) => translations.english[key],
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('english');

  useEffect(() => {
    const loadLanguage = async () => {
      try {
        const saved = await AsyncStorage.getItem('language');
        if (saved) {
          setLanguageState(saved as Language);
        }
      } catch (e) {
        console.error('Failed to load language', e);
      }
    };
    loadLanguage();
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    AsyncStorage.setItem('language', lang).catch((e) =>
      console.error('Failed to save language', e)
    );
  };

  const t = (key: keyof Translations) => {
    return translations[language][key] || translations.english[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);

